### ISSUE TITLE
Will locales be supported in algorithm messages as they are now in algorithm names?

### ISSUE THREAD

**Issue by serd2011** [UnickSoft/graphonline#27]
If so, where are the messages supposed to be located, in home.php?

**Comment by UnickSoft** [comment]
Algorithm messages are already in home.php (https://github.com/UnickSoft/graphonline/blob/master/lang/ru/home.php). You may try text search to find needed text, because algorithm messages don't have separate section in this file. For example: $g_lang['select_first_graph_isomorphism_check'] - is message for graph isomorphism.
